#!/usr/bin/env bash
# Copyright 2026 Ori Nexus Systems LTD
# SPDX-License-Identifier: Apache-2.0
#
# Refresh the vendored telemetry refusal contract.
#
# The contract is generated by the product API's own suite and vendored here so
# the runtime's classification can be replayed against it offline. Vendoring
# costs drift, and this is how drift is detected: it reports rather than
# silently overwrites.
#
# Unlike the ori-specs vectors, the source repository is private, so this
# cannot run in the runtime's public CI and is a maintainer check. The upstream
# gate is the generator itself, which fails the product API's CI if the live
# app stops producing the committed bytes. What public CI enforces here is the
# local-edit digest in tests/test_telemetry_refusal_contract.py.
#
# Usage:
#   ORI_ENERGY_DIR=/path/to/checkout bash scripts/refresh-telemetry-refusal-fixture.sh
#   ORI_VECTORS_APPLY=1 ORI_ENERGY_DIR=... bash scripts/refresh-telemetry-refusal-fixture.sh

set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
APPLY="${ORI_VECTORS_APPLY:-0}"
SRC_PATH="apps/api/tests/fixtures/runtime_contracts/telemetry_refusals.json"
DEST_DIR="${REPO}/tests/vectors/telemetry_refusals"
DEST="${DEST_DIR}/telemetry_refusals.json"
MANIFEST="${DEST_DIR}/MANIFEST.json"

if [ -z "${ORI_ENERGY_DIR:-}" ]; then
  echo "ORI_ENERGY_DIR must point at a checkout of the product API repository." >&2
  echo "It is private, so this check cannot clone it." >&2
  exit 2
fi
SRC_REPO="${ORI_ENERGY_DIR}"

if [ "${ORI_SKIP_FETCH:-0}" != "1" ]; then
  # Without this the check resolves whatever the clone last saw, and a stale
  # checkout reports "up to date" against a contract that has since moved.
  git -C "${SRC_REPO}" fetch --quiet origin 2>/dev/null || \
    echo "warning: could not fetch; comparing against the local clone" >&2
fi

MAIN_REF=""
for candidate in refs/remotes/origin/main refs/heads/main refs/heads/master; do
  if git -C "${SRC_REPO}" rev-parse --verify --quiet "${candidate}" >/dev/null; then
    MAIN_REF="${candidate}"
    break
  fi
done
if [ -z "${MAIN_REF}" ]; then
  echo "no main branch found in ${SRC_REPO}; cannot establish provenance" >&2
  exit 1
fi
MAIN="$(git -C "${SRC_REPO}" rev-parse "${MAIN_REF}")"

# Read from the resolved commit, never the working tree. A checkout on another
# branch or with uncommitted edits then cannot produce bytes whose recorded
# provenance is a commit that did not contain them.
if ! git -C "${SRC_REPO}" cat-file -e "${MAIN}:${SRC_PATH}" 2>/dev/null; then
  echo "${SRC_PATH} is not present at ${MAIN_REF} (${MAIN})" >&2
  exit 1
fi
UPSTREAM="$(mktemp)"
trap 'rm -f "${UPSTREAM}"' EXIT
git -C "${SRC_REPO}" show "${MAIN}:${SRC_PATH}" > "${UPSTREAM}"

# The commit that produced these bytes, not the tip. The pin stays true as main
# advances, so a documentation merge upstream does not stale every consumer.
SOURCE_COMMIT="$(git -C "${SRC_REPO}" log -1 --format=%H "${MAIN}" -- "${SRC_PATH}")"

digest() {
  python3 -c 'import hashlib,sys; print(hashlib.sha256(open(sys.argv[1],"rb").read()).hexdigest())' "$1"
}
UPSTREAM_DIGEST="$(digest "${UPSTREAM}")"

# The producer publishes its own digest beside the file. If that disagrees with
# the bytes, the upstream pin is broken and re-vendoring would carry the break.
SIDECAR="$(git -C "${SRC_REPO}" show "${MAIN}:${SRC_PATH}.sha256" 2>/dev/null | awk '{print $1}' || true)"
if [ -n "${SIDECAR}" ] && [ "${SIDECAR}" != "${UPSTREAM_DIGEST}" ]; then
  echo "BROKEN   upstream sidecar digest does not match upstream bytes" >&2
  echo "  sidecar records ${SIDECAR}" >&2
  echo "  bytes hash to   ${UPSTREAM_DIGEST}" >&2
  exit 1
fi

drift=0

if [ ! -f "${DEST}" ]; then
  echo "NEW      telemetry_refusals.json"
  drift=1
elif ! cmp -s "${UPSTREAM}" "${DEST}"; then
  echo "CHANGED  telemetry_refusals.json"
  drift=1
fi

PINNED=""
if [ -f "${MANIFEST}" ]; then
  PINNED="$(python3 -c 'import json,sys; print(json.load(open(sys.argv[1])).get("source_commit",""))' \
    "${MANIFEST}" 2>/dev/null || echo "")"
fi
if ! [[ "${PINNED}" =~ ^[0-9a-f]{40}$ ]]; then
  echo "PIN      source_commit is not a full commit id: '${PINNED}'"
  drift=1
elif ! git -C "${SRC_REPO}" cat-file -e "${PINNED}^{commit}" 2>/dev/null; then
  echo "PIN      pinned commit ${PINNED} is not in ${SRC_REPO}"
  drift=1
elif ! git -C "${SRC_REPO}" merge-base --is-ancestor "${PINNED}" "${MAIN}" 2>/dev/null; then
  echo "STALE    pinned commit ${PINNED} is not an ancestor of ${MAIN_REF}"
  drift=1
# Ancestry alone says the commit landed, not that it carried these bytes. A pin
# naming a commit where the file is absent, or held different content, is
# provenance pointing at nothing while reading as authoritative.
elif ! git -C "${SRC_REPO}" cat-file -e "${PINNED}:${SRC_PATH}" 2>/dev/null; then
  echo "PIN      ${SRC_PATH} does not exist at pinned commit ${PINNED}"
  drift=1
else
  PINNED_FILE="$(mktemp)"
  git -C "${SRC_REPO}" show "${PINNED}:${SRC_PATH}" > "${PINNED_FILE}"
  PINNED_DIGEST="$(digest "${PINNED_FILE}")"
  rm -f "${PINNED_FILE}"
  VENDORED_DIGEST=""
  [ -f "${DEST}" ] && VENDORED_DIGEST="$(digest "${DEST}")"
  if [ "${PINNED_DIGEST}" != "${VENDORED_DIGEST}" ]; then
    echo "PIN      pinned commit ${PINNED} does not carry the vendored bytes"
    echo "         at that commit: ${PINNED_DIGEST}"
    echo "         vendored here:  ${VENDORED_DIGEST}"
    drift=1
  fi
fi

if [ "${drift}" = "0" ]; then
  echo "up to date; vendored bytes pinned at ${PINNED}"
  if [ "${PINNED}" != "${SOURCE_COMMIT}" ]; then
    echo "note: the file last changed upstream at ${SOURCE_COMMIT}, which"
    echo "      carries the same bytes; the pin stays valid."
  fi
  exit 0
fi

if [ "${APPLY}" != "1" ]; then
  echo
  echo "Re-vendor with:"
  echo "  ORI_VECTORS_APPLY=1 ORI_ENERGY_DIR=${SRC_REPO} bash scripts/refresh-telemetry-refusal-fixture.sh"
  echo "Review the diff before committing: a changed status or meaning is a"
  echo "contract change and the runtime's classification may no longer be right."
  exit 1
fi

mkdir -p "${DEST_DIR}"
cp "${UPSTREAM}" "${DEST}"
python3 - "${SOURCE_COMMIT}" "${SRC_PATH}" "${DEST_DIR}" <<'PY'
import hashlib, json, pathlib, sys

commit, source, dest = sys.argv[1], sys.argv[2], pathlib.Path(sys.argv[3])
manifest = json.loads((dest / "MANIFEST.json").read_text())
manifest["source_commit"] = commit
manifest["source_path"] = source
manifest["files"] = {
    "telemetry_refusals.json": hashlib.sha256(
        (dest / "telemetry_refusals.json").read_bytes()
    ).hexdigest()
}
(dest / "MANIFEST.json").write_text(json.dumps(manifest, indent=2) + "\n")
PY
echo "re-vendored at ${SOURCE_COMMIT}"
